name: test_toolkit
description: A new Dart and Flutter test toolkit.
version: 0.1.0
#homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  test: ^1.24.3


dev_dependencies:
  lints: ^2.0.1
